name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ -Wall -Wextra -o sender-executable BMS_Data_Sender/BMS_Sender.cpp
      
    - name: run
      run: ./sender-executable
