name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      name: install coverage tool
      
    - name: build
      run: g++ -std=gnu++11 -Wall -Wextra -o sender-executable BMS_Data_Sender/*.cpp
 
    - name: run
      run: ./sender-executable
