name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      name: install coverage tool
      run: sudo apt-get install -y libboost-all-dev
      
    - name: build
      run: g++ -Wall -Wextra -o sender-executable -lboost_system -lboost_filesystem BMS_Data_Sender/*.cpp
      
    - name: run
      run: ./sender-executable
