name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: sudo apt-get install -y gcovr
     
     - name: build-test
      run: g++ -std=c++11 -Wall -Wextra -o test-executable Test_Sender/*.cpp BMS_Data_Sender/*.cpp
    
    - name: run
      run: ./test-executable
    
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
