name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: sudo apt-get install -y gcovr
      
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o sender-executable BMS_Data_Sender/*.cpp
    
    - name: build-test
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o test-executable BMS_Data_Sender/*.c* Test_Sender/*.c*
    
      - name: run
      run: ./test-executable
    
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
